FROM python:3.6.3

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory:
RUN mkdir -p /usr/src/app/code
WORKDIR /usr/src/app

#add requirements
ADD ./requirements.txt /usr/src/app/requirements.txt

# install requirments
RUN pip install -r requirements.txt

# add entrypoint.sh
ADD ./entrypoint.sh /usr/src/app/entrypoint.sh

# add app
ADD . /usr/src/app

#run server
CMD ["./entrypoint.sh"]

