# base image
FROM node:9.4

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/user/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
#adding src so that tests are available (if mounting local dirs worked, might not be needed)
COPY src /usr/src/app/src

RUN npm install  --silent
RUN npm install react-scripts@1.1.0 -g --silent

#start the app
CMD ["npm", "start"]
